export interface Category {
  slug: string;
  title: string;
  desc: string;
  image: string;
  photos: { src: string; alt: string }[];
}

export const categories: Category[] = [
  {
    slug: "kuhni",
    title: "Кухні",
    desc: "Функціональні та естетичні кухні, створені для вашого простору. Глянцеві та матові фасади, кам'яні стільниці, вбудована техніка.",
    image: "/gallery/kuhni/kuhni-1.jpg",
    photos: [
      { src: "/gallery/kuhni/kuhni-1.jpg", alt: "Сучасна кухня з білими глянцевими фасадами та кам'яною стільницею" },
      { src: "/gallery/kuhni/kuhni-2.jpg", alt: "Кухня з вбудованою духовкою та витяжкою" },
      { src: "/gallery/kuhni/kuhni-3.jpg", alt: "Кухня — загальний вигляд" },
      { src: "/gallery/kuhni/kuhni-4.jpg", alt: "Кухонні шафи та робоча зона" },
      { src: "/gallery/kuhni/kuhni-5.jpg", alt: "Матова кухня сірого кольору з чорною стільницею" },
      { src: "/gallery/kuhni/kuhni-6.jpg", alt: "Кухня L-подібної форми з темним фартухом" },
      { src: "/gallery/kuhni/kuhni-7.jpg", alt: "Кухня з варильною панеллю та мийкою" },
      { src: "/gallery/kuhni/kuhni-w1.jpg", alt: "Затишна кухня з посудомийкою" },
      { src: "/gallery/kuhni/kuhni-w2.jpg", alt: "Кухня з мийкою та шухлядами" },
      { src: "/gallery/kuhni/kuhni-w3.jpg", alt: "Кухонні фасади та стільниця" },
      { src: "/gallery/kuhni/kuhni-w4.jpg", alt: "Кухня з вбудованою технікою" },
      { src: "/gallery/kuhni/kuhni-w5.jpg", alt: "Робоча зона кухні" },
      { src: "/gallery/kuhni/kuhni-w6.jpg", alt: "Кухонні шафи та полиці" },
      { src: "/gallery/kuhni/kuhni-w7.jpg", alt: "Функціональна кухня з островом" },
      { src: "/gallery/kuhni/kuhni-w8.jpg", alt: "Кухонний острів зі стільницею" },
      { src: "/gallery/kuhni/kuhni-w9.jpg", alt: "Кухня з барною стійкою" },
      { src: "/gallery/kuhni/kuhni-w10.jpg", alt: "Кухонні шафи з підсвіткою" },
      { src: "/gallery/kuhni/kuhni-w11.jpg", alt: "Кухня — деталі інтер'єру" },
      { src: "/gallery/kuhni/kuhni-w12.jpg", alt: "Кухонна робоча поверхня" },
      { src: "/gallery/kuhni/kuhni-w13.jpg", alt: "Кухня з вбудованою духовкою" },
      { src: "/gallery/kuhni/kuhni-w14.jpg", alt: "Лаконічна кухня з підсвічуванням" },
      { src: "/gallery/kuhni/kuhni-w15.jpg", alt: "Кухня з LED-підсвіткою" },
      { src: "/gallery/kuhni/kuhni-w16.jpg", alt: "Кухонні фасади з матовим покриттям" },
      { src: "/gallery/kuhni/kuhni-w17.jpg", alt: "Кухня — загальний вигляд" },
      { src: "/gallery/kuhni/kuhni-w18.jpg", alt: "Кухня з темними фасадами" },
      { src: "/gallery/kuhni/kuhni-w19.jpg", alt: "Кутова кухня з глянцевими фасадами" },
      { src: "/gallery/kuhni/kuhni-w20.jpg", alt: "Глянцеві кухонні фасади" },
      { src: "/gallery/kuhni/kuhni-w21.jpg", alt: "Кухня з хромованими ручками" },
      { src: "/gallery/kuhni/kuhni-w22.jpg", alt: "Кухонна стільниця з каменю" },
      { src: "/gallery/kuhni/kuhni-w23.jpg", alt: "Кухня — деталі інтер'єру" },
      { src: "/gallery/kuhni/kuhni-w24.jpg", alt: "Велика кухня з барною стійкою" },
      { src: "/gallery/kuhni/kuhni-w25.jpg", alt: "Барна стійка на кухні" },
      { src: "/gallery/kuhni/kuhni-w26.jpg", alt: "Кухня з відкритими полицями" },
      { src: "/gallery/kuhni/kuhni-w27.jpg", alt: "Кухонні шафи та техніка" },
      { src: "/gallery/kuhni/kuhni-w28.jpg", alt: "Кухня — загальний вигляд" },
      { src: "/gallery/kuhni/kuhni-w33.jpg", alt: "Кухня з вбудованою технікою" },
      { src: "/gallery/kuhni/kuhni-w34.jpg", alt: "Кухонні фасади та стільниця" },
      { src: "/gallery/kuhni/kuhni-w37.jpg", alt: "Кухня — деталі інтер'єру" },
      { src: "/gallery/kuhni/kuhni-w38.jpg", alt: "Кухня з підсвіткою" },
      { src: "/gallery/kuhni/kuhni-w39.jpg", alt: "Кухонні фасади" },
      { src: "/gallery/kuhni/kuhni-w40.jpg", alt: "Кухня — загальний вигляд" },
    ],
  },
  {
    slug: "vanni",
    title: "Ванні кімнати",
    desc: "Меблі для ванних кімнат з вологостійких матеріалів. Тумби під раковину, навісні шафи, полички з підсвіткою.",
    image: "/gallery/vanni/vanni-1.jpg",
    photos: [
      { src: "/gallery/vanni/vanni-1.jpg", alt: "Навісна шафа для ванної кімнати" },
      { src: "/gallery/vanni/vanni-2.jpg", alt: "Тумба під раковину з мармуровою стільницею" },
      { src: "/gallery/vanni/vanni-3.jpg", alt: "Висока шафа у ванній кімнаті" },
      { src: "/gallery/vanni/vanni-4.jpg", alt: "Сіра ванна з дзеркалом на підсвітці" },
      { src: "/gallery/vanni/vanni-5.jpg", alt: "Ванна кімната з круглим дзеркалом та LED-підсвіткою" },
      { src: "/gallery/vanni/vanni-6.jpg", alt: "Тумба під раковину з дерев'яними полицями" },
      { src: "/gallery/vanni/vanni-7.jpg", alt: "Дерев'яні полички з підсвіткою над раковиною" },
      { src: "/gallery/vanni/vanni-8.jpg", alt: "Ванна кімната з душовою зоною" },
    ],
  },
  {
    slug: "vitalni",
    title: "Вітальні",
    desc: "Шафи, комоди, полиці та системи зберігання для вітальні. ТВ-тумби, вітрини, настінні полиці.",
    image: "/gallery/vitalni/vitalni-1.jpg",
    photos: [
      { src: "/gallery/vitalni/vitalni-1.jpg", alt: "ТВ-тумба з полицями" },
      { src: "/gallery/vitalni/vitalni-2.jpg", alt: "Вітрина зі скляними полицями та підсвіткою" },
      { src: "/gallery/vitalni/vitalni-5.jpg", alt: "Білий комод з рифленими фасадами та золотими ніжками" },
      { src: "/gallery/vitalni/vitalni-6.jpg", alt: "Комод — фронтальний вигляд" },
      { src: "/gallery/vitalni/vitalni-7.jpg", alt: "Настінні полиці та комод з робочою зоною" },
      { src: "/gallery/vitalni/vitalni-8.jpg", alt: "Система настінних полиць різних розмірів" },
      { src: "/gallery/vitalni/vitalni-w2.jpg", alt: "ТВ-зона з полицями та шафами" },
      { src: "/gallery/vitalni/vitalni-w3.jpg", alt: "Класична ТВ-тумба" },
      { src: "/gallery/vitalni/vitalni-w4.jpg", alt: "ТВ-зона — загальний вигляд" },
      { src: "/gallery/vitalni/vitalni-w5.jpg", alt: "ТВ-зона з підсвіткою" },
      { src: "/gallery/vitalni/vitalni-w6.jpg", alt: "Компактна вітальня з вітриною" },
      { src: "/gallery/vitalni/vitalni-w7.jpg", alt: "Вітрина зі скляними полицями" },
      { src: "/gallery/vitalni/vitalni-w23.jpg", alt: "Вітальня — загальний вигляд" },
      { src: "/gallery/vitalni/vitalni-w24.jpg", alt: "Вітальня з полицями" },
      { src: "/gallery/vitalni/vitalni-w25.jpg", alt: "Вітальня — деталі інтер'єру" },
      { src: "/gallery/vitalni/vitalni-w26.jpg", alt: "Вітальня з комодом" },
      { src: "/gallery/vitalni/vitalni-w27.jpg", alt: "Класична шафа з фасадами-решітками" },
      { src: "/gallery/vitalni/vitalni-w28.jpg", alt: "Шафа з латунними ручками" },
      { src: "/gallery/vitalni/vitalni-w29.jpg", alt: "Меблі для вітальні" },
    ],
  },
  {
    slug: "spalni",
    title: "Спальні",
    desc: "Ліжка, тумби, комоди та гардеробні для комфортного відпочинку. Вбудовані шафи, туалетні столики.",
    image: "/gallery/spalni/spalni-1.jpg",
    photos: [
      { src: "/gallery/spalni/spalni-1.jpg", alt: "Туалетний столик з дзеркалом" },
      { src: "/gallery/spalni/spalni-2.jpg", alt: "Приліжкові тумбочки" },
      { src: "/gallery/spalni/spalni-3.jpg", alt: "Шафа-купе з матовими дверима" },
      { src: "/gallery/spalni/spalni-4.jpg", alt: "Інтер'єр шафи-купе з полицями та штангами" },
      { src: "/gallery/spalni/spalni-5.jpg", alt: "Біла шафа зі скляними чорними секціями" },
      { src: "/gallery/spalni/spalni-6.jpg", alt: "Шафа — загальний вигляд" },
      { src: "/gallery/spalni/spalni-7.jpg", alt: "Шафа з відкритою скляною дверкою та дерев'яними полицями" },
      { src: "/gallery/spalni/spalni-w1.jpg", alt: "Сірі меблі у спальню" },
      { src: "/gallery/spalni/spalni-w2.jpg", alt: "Спальня з сірими фасадами" },
      { src: "/gallery/spalni/spalni-w3.jpg", alt: "Спальня — загальний вигляд" },
      { src: "/gallery/spalni/spalni-w4.jpg", alt: "Сіра шафа у спальні" },
      { src: "/gallery/spalni/spalni-w5.jpg", alt: "Спальня з вбудованою шафою" },
      { src: "/gallery/spalni/spalni-w6.jpg", alt: "Спальня — деталі інтер'єру" },
      { src: "/gallery/spalni/spalni-w7.jpg", alt: "Спальня з приліжковими тумбочками" },
      { src: "/gallery/spalni/spalni-w8.jpg", alt: "Спальня — загальний вигляд" },
      { src: "/gallery/spalni/spalni-w9.jpg", alt: "Спальня з темними елементами" },
      { src: "/gallery/spalni/spalni-w10.jpg", alt: "Спальня — деталі інтер'єру" },
      { src: "/gallery/spalni/spalni-w11.jpg", alt: "Дводверна шафа-купе з вбудованими шухлядами" },
      { src: "/gallery/spalni/spalni-w12.jpg", alt: "Шафа-купе — загальний вигляд" },
      { src: "/gallery/spalni/spalni-w13.jpg", alt: "Шафа-купе з полицями" },
      { src: "/gallery/spalni/spalni-w14.jpg", alt: "Шафа-купе — деталі інтер'єру" },
      { src: "/gallery/spalni/spalni-w15.jpg", alt: "Місткі меблі у спальню" },
      { src: "/gallery/spalni/spalni-w16.jpg", alt: "Спальня — загальний вигляд" },
      { src: "/gallery/spalni/spalni-w17.jpg", alt: "Спальня з вішаками та дзеркалом" },
      { src: "/gallery/spalni/spalni-w18.jpg", alt: "Спальня — деталі інтер'єру" },
      { src: "/gallery/spalni/spalni-w19.jpg", alt: "Спальня з шафою та лавкою" },
      { src: "/gallery/spalni/spalni-w20.jpg", alt: "Спальня — загальний вигляд" },
      { src: "/gallery/spalni/spalni-w21.jpg", alt: "Спальня з шафою" },
      { src: "/gallery/spalni/spalni-w23.jpg", alt: "Спальня — деталі інтер'єру" },
      { src: "/gallery/spalni/spalni-w24.jpg", alt: "Спальня з полицями" },
      { src: "/gallery/spalni/spalni-w25.jpg", alt: "Спальня — загальний вигляд" },
      { src: "/gallery/spalni/spalni-w26.jpg", alt: "Спальня з вбудованою шафою" },
      { src: "/gallery/spalni/spalni-w27.jpg", alt: "Шафа — деталі інтер'єру" },
      { src: "/gallery/spalni/spalni-w28.jpg", alt: "Спальня з підсвіткою" },
      { src: "/gallery/spalni/spalni-w29.jpg", alt: "Меблі для дитячої кімнати" },
    ],
  },
  {
    slug: "prikhozha",
    title: "Прихожі",
    desc: "Вбудовані шафи, комоди та системи зберігання для прихожої. Лавки, вішаки, дзеркала.",
    image: "/gallery/prikhozha/prikhozha-1.jpg",
    photos: [
      { src: "/gallery/prikhozha/prikhozha-1.jpg", alt: "Вбудована шафа з лавкою та вішаками" },
      { src: "/gallery/prikhozha/prikhozha-2.jpg", alt: "Шафа з розсувними дверима та ліпниною" },
      { src: "/gallery/prikhozha/prikhozha-3.jpg", alt: "Лавка з м'якою подушкою та гачками" },
      { src: "/gallery/prikhozha/prikhozha-4.jpg", alt: "Верхня шафа з відкритою дверкою" },
      { src: "/gallery/prikhozha/prikhozha-5.jpg", alt: "Інтер'єр шафи з полицями та штангами" },
      { src: "/gallery/prikhozha/prikhozha-6.jpg", alt: "Шафа — внутрішній простір з полицями" },
      { src: "/gallery/prikhozha/prikhozha-w7.jpg", alt: "Місткі меблі у передпокій" },
      { src: "/gallery/prikhozha/prikhozha-w8.jpg", alt: "Передпокій — загальний вигляд" },
      { src: "/gallery/prikhozha/prikhozha-w9.jpg", alt: "Передпокій з вішаками та дзеркалом" },
      { src: "/gallery/prikhozha/prikhozha-w10.jpg", alt: "Передпокій — деталі інтер'єру" },
      { src: "/gallery/prikhozha/prikhozha-w11.jpg", alt: "Передпокій з шафою та лавкою" },
      { src: "/gallery/prikhozha/prikhozha-w12.jpg", alt: "Вбудована шафа з лавкою та дзеркалом" },
      { src: "/gallery/prikhozha/prikhozha-w13.jpg", alt: "Шафа-купе з дзеркальними дверима" },
    ],
  },
];

export function getCategoryBySlug(slug: string): Category | undefined {
  return categories.find((c) => c.slug === slug);
}
